### ISSUE TITLE
Practica Hilos

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/practica-de-hilos-Band-hi#2]
[Practica de Hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Band-hi/files/6495297/Practica.de.Hilos.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 20

Calificó: Imanol García, Israel Nicolás y Uzias López

**Comment by josealfredo79** [comment]
Bien hecho y revisado
